### ISSUE TITLE
simplex projection

### ISSUE THREAD

**Issue by brzkhv** [Marigold/universal-portfolios#10]
Hello @akaniklaus. Sorry, I don't have exactly an issue but a question regarding simplex projection.
I tried to contact the authors of PAMR paper but it seem their email address is not valid anymore so I thought that I would ask you.
I was wondering that relaxing the non-negativity constraint and then projecting the solution keeps the optimality of the solution? and if we try to solve the problem with the non-negativity constraint with a numerical solver, does it yield better results?
Thanks

**Comment by akaniklaus** [comment]
Hello, I am using a SoftPlus activation function instead of Simplex as it enables a better portfolio diversification. It might not perform as good as Simplex in backtests but I believe that there are some significant advantages in live-trading.
