### ISSUE TITLE
It seem like the two functions "run" and "run_combination" do not calculate the same the total_wealth?

### ISSUE THREAD

**Issue by gitwildpig** [Marigold/universal-portfolios#100]
It started when I needed to do a sensitivity analysis of the parameters A and B for a strategy, so I took a column of values for each of the two parameters, and calculated the `total_wealth` of the strategy given their combination by the `run_combination()`. But I found that the total_wealth result of the `run_combination()` function is not the same as the result of `run()` with one pair parameter.

For example, i want to analysis the sensitivity of `eps` and `tau` for `RMR` strategy in `msci` dataset, so i set `eps = [5, 7, 10]` and `tau = [0.001, 0.003, 0.005]`. For each `eps"`, I use the `run_combination()` function to calculate total_wealth for `tau = [0.001, 0.003, 0.005]`. So i can get these `total_wealth` results, as follows:

| RMR in msci dataset | tau=0.001 | tau=0.003 | tau=0.005 |
| ------------------- | --------- | --------- | --------- |
| eps=5               | 15.265134 | 14.582517 | 14.581872 |
| eps=7               | 15.265134 | 14.582517 | 14.581872 |
| eps=10              | 15.265134 | 14.582517 | 14.581872 |

here is my code

```python
from universal.algos.rmr import RMR
import pandas as pd

# set parameters
eps_s = [5, 7, 10]
tau_s = [0.001, 0.003, 0.005]
# choose dataset
names = "msci"
# storage total_wealth matrix for parameter pairs
df = pd.DataFrame(columns=tau_s)
data = pd.read_excel(f'./data/{names}.xlsx')
for pm in eps_s:
    # import RMR strategy
	algo = RMR(window=5, eps=pm, tau=0.001)
    # run RMR combination with a list tau and a fixed eps 
	result = algo.run_combination(data, tau=tau_s)
  	# get the total_wealth
    temp = result.to_dataframe()
    temp.columns = tau_s
    # storage total_wealth list for fixed eps
    df.loc[pm] = temp.iloc[-1]

# print heatmap table
print(df)
```

I found that the `total_wealth` calculated with the `run_combination()` function were not the same as the `total_wealth` I calculated with the `run()` function for each pair `(eps, tau)`. **I want to know why?**

Here are the `total_wealth` I calculated for each pair `(eps, tau)` using the `run()` function, and my code is also below.

| RMR in msci dataset | tau=0.001          | tau=0.003          | tau=0.005          |
| ------------------- | ------------------ | ------------------ | ------------------ |
| eps=5               | 15.650054762878227 | 14.481360055700774 | 14.277005188960896 |
| eps=7               | 15.308675294773685 | 14.568359838690252 | 14.511553233978884 |
| eps=10              | 15.265133635623464 | 14.58251697521352  | 14.581872301158764 |

```python
from universal.algos.rmr import RMR
import pandas as pd

# set parameters
eps_s = [5, 7, 10]
tau_s = [0.001, 0.003, 0.005]
# choose dataset
names = "msci"
# storage total_wealth matrix for parameter pairs
df = pd.DataFrame(columns=tau_s, index=eps_s)
data = pd.read_excel(f'./data/{names}.xlsx')
for e in eps_s:
    for t in tau_s:
        # import RMR strategy
        algo = RMR(window=5, eps=e, tau=t)
        # run RMR with a pair of (eps,tau)
        result = algo.run(data)
        # storage total_wealth for parameters
        df.loc[e, t] = result.total_wealth

# print heatmap table
print(df)
```

**Comment by Marigold** [comment]
Hey @gitwildpig  The reason it's showing same values for all `eps` is that `run_combination` is meant to be run as a classmethod and it uses default parameters from __init__ (in this case eps=10).

You could run it as this to get heatmap of wealth
```python
list_result = RMR.run_combination(data, window=5, eps=eps_s, tau=tau_s)
# a bit hacky way to parse names into dictionary... I'm not proud of myself
df = [eval(f"dict({name}, wealth={result.total_wealth})") for result, name in zip(list_result, list_result.names)]
pd.DataFrame(df).pivot('eps', 'tau', 'wealth')
```

The benefit of running `run_combination` is that it runs in parallel (which can give you ~2x speedup) and `ListResult` has some fancy plotting methods. Unless you need them, your approach with two for loops is good enough.

**Comment by gitwildpig** [comment]
Hi! @Marigold I got it! Thank you for your kind codes and the suggestions! : )
I misunderstood `run_combination` before, thanks for the answer, good luck~

**Comment by Marigold** [comment]
@gitwildpig forgot to mention that I published new version 0.4.12 to PyPi. It has a fix for `run_combination` (previously it ran really slow...) and also fix for RMR (I don't understand how you got it to work 🤷)

**Comment by gitwildpig** [comment]
Hi @Marigold~ I'm very interested in what you mentioned, but I not sure if I understand it correctly. I looked at your update log for the `run_combination` function, and it looks like it just removes the function `results = map()` under the multiprocessing function `results = pool.map()`?🤔 If that's the case, the original version works, but `results = pool.map()` runs first, and then `results = map()` runs under a single thread, the return of `results = map()` overwrites the previous return of `results = pool.map()`, which takes more time, but the results should not be affected. The `rmr` code update seems to just standardize the code format? It doesn't affect the structure of `rmr`. The new `olmar` further refines the relative price prediction methods, distinguishing between `SMA` and `EMA` prediction methods? `rmr` inherits the class of `olmar`, but its prediction method is independent of `olmar`, so I think the previous version of `rmr` is ok to use, acturally, `olmar` is ok, too. 
[PS: The amount of code in this repository is really huge, I have to keep reading it:joy. Anyway, your code is awesome🚀.]

**Comment by Marigold** [comment]
Nice! I'm glad there's at least one person capable of understanding the code I wrote 8 years ago :).

> and it looks like it just removes the function results = map() under the multiprocessing function results = pool.map()?

Yeah, that was a silly mistake. It probably creeped in when I was debugging something. I ran the same thing twice, once with `pool.map` and once with `map`.

> The rmr code update seems to just standardize the code format?

I was actually getting an error, so glad that it was working for you.

**Comment by gitwildpig** [comment]
I'm also very happy, in fact I've been looking the rmr code on my local computer (I haven't updated it yet, because I added some functions in it for myself), and I haven't found anything wrong for now (or maybe I didn't look hard enough). 
So I can not guess what problems you encountered before, perhaps a package version conflict? 
Anyway, the most important thing is to know that you have solved the problem that was bothering you.
