### ISSUE TITLE
Question about data format

### ISSUE THREAD

**Issue by catgrandpas** [Marigold/universal-portfolios#102]
Hello! I've been reviewing your code and noticed that the algo.run() function expects the input data type to be raw, and then it automatically converts it into the appropriate data format internally. However, I'm wondering why, in the provided OLMAR example, NYSE(O) data is used as relative price data. Is there a specific reason for this, or is it potentially an issue?

**Comment by Marigold** [comment]
Hmm, I'm not sure if I understand the question. NYSE(O) data is in raw format (just normalized so that the starting price is 1). OLMAR then converts the data and work with it.

**Comment by catgrandpas** [comment]
Okay, I understand your point now. I had this question because when I used the Universal Portfolios algorithm to run classic datasets, I noticed that the backtest results for the same strategy on the same dataset were different. I'm not sure if it's due to different initial parameter settings or because of differences between MATLAB and Python. Either way, thank you again for your response and contribution

**Comment by Marigold** [comment]
> I'm not sure if it's due to different initial parameter settings or because of differences between MATLAB and Python.

It could be many things... It's typically tough to replicate the results exactly. You are usually lucky if your results are at least directionally correct as results from the paper.
