### ISSUE TITLE
Data reference

### ISSUE THREAD

**Issue by gabriel-turinici** [Marigold/universal-portfolios#105]
Hi,

I'm interested to use some algorithms and the data to compare with my ongoing research and other algos from the literature. Is there any indication on what each dataset corresponds to ? For instance, is "nyse_o" the reference mentioned in Section 5 of 'On-Line Portfolio Selection Using Multiplicative Updates' ? Are stocks given in the order set in the footnote (same page) ? BTW I guess prices were translated into multiplicative factors. Any hint for the other datasets welcome.

best regards and thank you for this nice package !
Gabriel

**Comment by Marigold** [comment]
Hi Gabriel, the `nyse_o` dataset is indeed the one from Section 5 of Helmbold. Unfortunately, I don't remember where I got it from and I don't think columns match the footnote in the paper. Despite being a benchmark for many papers, I personally think this dataset isn't very representative of empirical validation. The [other datasets](https://github.com/Marigold/universal-portfolios/tree/master/universal/data) are slightly better, but also often cherry picked.

If you check out newer papers there should be links to available datasets.

**Comment by gabriel-turinici** [comment]
thank you for the reply and confirmation, indeed some info and datasets are in papers. And I agree that somehow the data is cherry picked, the general performance of this type of algorithm is very diverse.
