### ISSUE TITLE
min_history for CORN

### ISSUE THREAD

**Issue by stergnator** [Marigold/universal-portfolios#11]
Hi @Marigold,

I am experiencing reproducibility issues when using different values for min_history on the CORN algorithm.  I have narrowed the issue down to how the X_t and X_i objects (lines 104 & 105) are created in algos/corn.py .  

I wonder if I don't understand what min_history is supposed to accomplish?  Here's how I understand min_history to work.  Let's say I am using 10 years of daily data starting from 1/1/2008 up to an including all of 2017, and I only want to solve for the weights for the last 4 weeks in 2017.  To do this I set algo.min_history = returns.shape[0] - 20, and then call algo.run(returns).

The problem arrises when I now want to find the weights for the last 8 weeks in 2017.  This time I set algo.min_history = returns.shape[0] - 40.  I expect the weights for the 20 days in December that both problem formulations share to be the same, but they are not.

Am I understanding the use of min_history properly?

Thanks in advance,

Stergios

**Comment by Marigold** [comment]
You are understanding it properly (btw here's docstring just for completeness)
```
:param min_history: If not None, use initial weights for first min_window days. Use
            this if the algo needs some history for proper parameter estimation.
```

The reason why weights differ is:
a) At time `t - 20` CORN will start on-line updating using **uniform weights** from time `t - 21`
b) CORN will start computing at `t - 40`, so at time `t - 21` the weights will be far from uniform. CORN will however use them to calculate weights at time `t - 20`

Does it make sense? If not, could you please post reproducible example? Thanks

**Comment by stergnator** [comment]
I think I found the problem.  It is on line 63 in corn.py .  I changed

`self.t = -1`
to
`self.t = self.min_history - 1`

Stergios
