### ISSUE TITLE
 from pandas.stats.moments import rolling_mean as rolling_m ModuleNotFoundError: No module named 'pandas.stats'

### ISSUE THREAD

**Issue by SpiryMedia** [Marigold/universal-portfolios#15]
```
    from universal import tools
  File "C:\spiry.ai\envs\dlwin36\lib\site-packages\universal_portfolios-0.3.2-py3.6.egg\universal\tools.py", line 5, in <module>
    from pandas.stats.moments import rolling_mean as rolling_m
ModuleNotFoundError: No module named 'pandas.stats'
```
I am running a code that uses universal-portfolio as library but I get this error that seems to come from universal-portfolios itself.

**Comment by Marigold** [comment]
Hm, pandas library made some breaking changes in version 0.23. Could you either run `pip install pandas==0.22.0` or reinstall `universal-portfolios` (I've updated the version on PyPi)?

**Comment by SpiryMedia** [comment]
I will try it, but already move-on of using universal-portfolios. 

Thanks for support!

**Comment by windwine** [comment]
reverting back to 0.22.0 is messing up with other pd functions. Is there a way to work around it? THX.
