### ISSUE TITLE
Data information

### ISSUE THREAD

**Issue by swishderzy** [Marigold/universal-portfolios#17]
Hi,
It would be great to know about the granularity and time frame of the data, and the transformations done to these stocks prices.

Thank you.

**Comment by Marigold** [comment]
What data are you referring to?

**Comment by swishderzy** [comment]
The .pkl data in:   universal/data/

**Comment by Marigold** [comment]
It's daily. Just be aware that it's more than 5 years old.

**Comment by swishderzy** [comment]
- Can you tell me the time frame of these data (from date to date).
- And what kind of transformations you did on these prices (from simple prices values to their actual state), it's clearly absolute prices but how exactly did you compute these absolute prices ?

**Comment by Marigold** [comment]
I don't remember to be honest. You can do
```
import pickle
with open('universal/data/djia.pkl', 'r') as f:
    df = pickle.load(f)
df.head()
```
and check for yourself.
