### ISSUE TITLE
ModuleNotFoundError: No module named 'algos'

### ISSUE THREAD

**Issue by gt1967** [Marigold/universal-portfolios#19]
Hello !
Trying to test the onlineportfolio.ipynb and got this error:
_ModuleNotFoundError: No module named 'algos'_
It's related to the ucrp flag in result.plot(weights=False, assets=False, ucrp=**True**, logy=True); in effect If I set ucrp = **False** I don't get the error, but of course I don't see the ucrp graph.
Thank you for your good work.

**Comment by Marigold** [comment]
Sure, I'll look into it.

**Comment by gt1967** [comment]
Solved. It would be enough to write on line 385 of result.py:
from **.**algos import CRP
Instead of:
from algos import CRP
Do the same at row 297 and 393

BTW I had to restart the kernel to see the effect on my jupyter notebook

**Comment by dexhunter** [comment]
same issue 
![image](https://user-images.githubusercontent.com/6930518/68525398-06fdab00-030c-11ea-9a2a-f7540f87b4e3.png)
But did not solved by changing to `**.**algo`. Are there any other solutions? thanks!
