### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by mdelvaux** [Marigold/universal-portfolios#2]
Trying to install, I got the error message below.  I am no expert in python install, trying to dig I can confirm that the file requirements.txt is not present in the temporary directory used by pip, but it is present in a (manually downloaded) ZIP file.

C:\Users\mdelvaux\AppData\Local\Continuum\Anaconda3\UniversalPortfolioMarigold>pip install --no-clean --no-deps  --no-cache universal-portfolios
Collecting universal-portfolios
  Downloading universal-portfolios-0.1.tar.gz (3.7MB)
    100% |################################| 3.7MB 13.7MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "C:\Users\mdelvaux\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\download.py", line 412, in get_file_content
        with open(url) as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\mdelvaux\AppData\Local\Temp\pip-build-sjzx1yfs\universal-portfolios\setup.py", line 6, in <module>
        reqs = [str(ir.req) for ir in install_reqs]
      File "C:\Users\mdelvaux\AppData\Local\Temp\pip-build-sjzx1yfs\universal-portfolios\setup.py", line 6, in <listcomp>
        reqs = [str(ir.req) for ir in install_reqs]
      File "C:\Users\mdelvaux\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\req\req_file.py", line 77, in parse_requirements
        filename, comes_from=comes_from, session=session
      File "C:\Users\mdelvaux\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\download.py", line 416, in get_file_content
        'Could not open requirements file: %s' % str(exc)
    pip.exceptions.InstallationError: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\mdelvaux\AppData\Local\Temp\pip-build-sjzx1yfs\universal-portfolios

**Comment by Marigold** [comment]
I'm not really sure what can cause this, but installing python packages from ZIP is not the preferred way. The best way is to install it via `pip install universal-portfolios` or directly from github with `pip install git+https://github.com/Marigold/universal-portfolios.git`.

By the way great work on your [logopt package](http://r-forge.r-project.org/projects/logopt/), I got heavily inspired by it.

**Comment by mdelvaux** [comment]
Hi Marigold, thanks for the kind words.

Installation also fails with the other approaches.  I only did try to use
the zip approach to get better diagnostic.  Here is what happens with the
other commands (this is on a different machines but all of them use
Anaconda with python 3).  The main cause seems to be that requirements.txt
is not present in the temporary directory used by pip, i.e. where it
expands the zip file?  I am not very familiar with the python installation
tools I am afraid.

I am working on trading strategies involving VIX futures, I have written a
number of simple tools in python, mostly to get data and some simple
visualization, but I want to start doing some optimization, in particular
some simple CRP, hence my need for your library.  I could go back to R, but
I prefer python more and more.

Result with pip install itself below, using git fails for me (cannot find
command git, I am on Windows and do have some git tools, but apparently
this is not sufficient for pip).

C:\Anaconda3>pip install universal-portfolios
Downloading/unpacking universal-portfolios
  Running setup.py
(path:C:\Users\mdelvaux\AppData\Local\Temp\pip_build_mdelvaux\universal-portfolios\setup.py)
egg_info for package universal-portfolios
    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\pip\download.py", line 274, in
get_file_content
        f = open(url)
    FileNotFoundError: [Errno 2] No such file or directory:
'requirements.txt'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File
"C:\Users\mdelvaux\AppData\Local\Temp\pip_build_mdelvaux\universal-portfolios\setup.py",
line 6, in <module>
        reqs = [str(ir.req) for ir in install_reqs]
      File
"C:\Users\mdelvaux\AppData\Local\Temp\pip_build_mdelvaux\universal-portfolios\setup.py",
line 6, in <listcomp>
        reqs = [str(ir.req) for ir in install_reqs]
      File "C:\Anaconda3\lib\site-packages\pip\req.py", line 1546, in
parse_requirements
        session=session,
      File "C:\Anaconda3\lib\site-packages\pip\download.py", line 278, in
get_file_content
        raise InstallationError('Could not open requirements file: %s' %
str(e))
    pip.exceptions.InstallationError: Could not open requirements file:
[Errno 2] No such file or directory: 'requirements.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "C:\Anaconda3\lib\site-packages\pip\download.py", line 274, in
get_file_content

    f = open(url)

FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File
"C:\Users\mdelvaux\AppData\Local\Temp\pip_build_mdelvaux\universal-portfolios\setup.py",
line 6, in <module>

    reqs = [str(ir.req) for ir in install_reqs]

  File
"C:\Users\mdelvaux\AppData\Local\Temp\pip_build_mdelvaux\universal-portfolios\setup.py",
line 6, in <listcomp>

    reqs = [str(ir.req) for ir in install_reqs]

  File "C:\Anaconda3\lib\site-packages\pip\req.py", line 1546, in
parse_requirements

    session=session,

  File "C:\Anaconda3\lib\site-packages\pip\download.py", line 278, in
get_file_content

    raise InstallationError('Could not open requirements file: %s' % str(e))

pip.exceptions.InstallationError: Could not open requirements file: [Errno
2] No such file or directory: 'requirements.txt'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in
C:\Users\mdelvaux\AppData\Local\Temp\pip_build_mdelvaux\universal-portfolios
Storing debug log for failure in C:\Users\mdelvaux\pip\pip.log

**Comment by Marigold** [comment]
Oh, I missed that you're using python 3. Currently works only with python 2.7+, not with python 3. I'm planning a new release in 2 weeks so I'll try to make it compatible. Until then you can use [anaconda environments](http://www.continuum.io/blog/conda), something like this should do the trick
```
conda create -n py2 anaconda
source activate py2
pip install universal-portfolios
```

**Comment by Marigold** [comment]
Added python compatibility to master plus tons of new improvements (see this [notebook for demonstration](http://nbviewer.ipython.org/github/Marigold/universal-portfolios/blob/master/modern-portfolio-theory.ipynb) if interested).
