### ISSUE TITLE
Kelly

### ISSUE THREAD

**Issue by firmai** [Marigold/universal-portfolios#22]
Hi, I know you are not actively working on this project, but I was wondering from your own experience if you have ever gotten the kelly algo to work? 

Best regards,
Derek

**Comment by Marigold** [comment]
> ...if you have ever gotten the kelly algo to work?

It all depends on your inputs - mean return and covariance matrix estimates. If your estimates are crap (like historical means), so will be kelly portfolio.

**Comment by firmai** [comment]
Excellent thanks.

**Comment by Marigold** [comment]
Check out this article https://investresolve.com/blog/portfolio-optimization-simple-optimal-methods/, it's an excellent overview of portfolio allocation methods.

**Comment by firmai** [comment]
Excellent thanks :)
