### ISSUE TITLE
Duplicate import comb in algo.py

### ISSUE THREAD

**Issue by angonyfox** [Marigold/universal-portfolios#26]
https://github.com/Marigold/universal-portfolios/blob/e2c147b128e9fdbf912ab8aa1d860406a4c62d37/universal/algo.py#L9 should be remove because https://github.com/Marigold/universal-portfolios/blob/e2c147b128e9fdbf912ab8aa1d860406a4c62d37/universal/algo.py#L11-L14 will import comb

**Comment by Marigold** [comment]
Yep, you're right. Feel free to add it to your PR or otherwise I'm gonna fix it in my next PR.
