### ISSUE TITLE
Strategy of "Best "

### ISSUE THREAD

**Issue by hanseul-jeong** [Marigold/universal-portfolios#34]
Hi, thanks for well-organized code

I have a question about **Best** strategy  
**BestSoFar** seems to be different from **classic best method**  

> I refer to [this survey](https://arxiv.org/abs/1212.2129)  

If **BestSoFar** is different strategy, could you tell me a definition or details?  

Thanks!

**Comment by Marigold** [comment]
>  Another widely adopted benchmark is the Best Stock (Best) strategy, which is a special BAH strategy that puts all capital on the stock with best performance in hindsight (article)

The difference is that `Best` selects a strategy **in hindsight** and `BestSoFar` only looks at the history and selects a strategy with the best performance **up to date**.

**Comment by hanseul-jeong** [comment]
Thanks for comments !
