### ISSUE TITLE
Code de-deprecation

### ISSUE THREAD

**Issue by anaderi** [Marigold/universal-portfolios#36]
There is a function in `tools.py` that has been deprecated long-time ago. 
```python
def rolling_cov_pairwise(df, *args, **kwargs):
    d = {}
    for c in df.columns:
        d[c] = pd.rolling_cov(df[c], df, *args, **kwargs)
    p = pd.Panel(d)
    return p.transpose(1, 0, 2)
```

I believe if one replaces it with 
`return df.rolling(kwargs['window']).cov(other=df, pairwise=True)`
then access to the S matrix would look like `df[name].unstack()`. Or am I missing something?

**Comment by Marigold** [comment]
That's correct. As you may have noticed, not all parts of this library are up to date and the test coverage is quite poor... I'll fix it when I have some extra time. Is something not working because of this?

**Comment by anaderi** [comment]
nothing terrible is happening with those outdates, but I find this library really nicely designed and written. So wanted to help it to be up2date.

**Comment by Marigold** [comment]
> but I find this library really nicely designed and written
haha, I would say exactly the opposite :D thanks though, I'm gonna fix it in next version

**Comment by alexander-myltsev** [comment]
@Marigold thanks for the descent work.

Could you create a space (gitter, slack, or else) where the community can ask you questions on how to run the stuff? It basically doesn't work at several places.

**Comment by Marigold** [comment]
Github issues is the right place, I unfortunately don't have time to give realtime support. If you describe the issues I'll try to find some time to fix them.

**Comment by alexander-myltsev** [comment]
@Marigold I made PR https://github.com/Marigold/universal-portfolios/pull/40
