### ISSUE TITLE
The isinstance checks if cov_estimator and mu_estimator are strings in mpt.py are Python 2 only

### ISSUE THREAD

**Issue by ricpruss** [Marigold/universal-portfolios#4]
The isinstance checks if cov_estimator and mu_estimator are strings in mpt.py are Python 2 only.

I have just changed basestring to str on lines 49 and 63, but I it looks as if you need something more complex to be compatible with both versions of python.
http://stackoverflow.com/questions/11301138/how-to-check-if-variable-is-string-with-python-2-and-3-compatibility.

Thanks for a wonderful work, and open sourcing this,
Ric

**Comment by Marigold** [comment]
Thanks for spotting this (shame on me for not writing tests). I fixed it in master & on PyPi (along with other minor improvements).
