### ISSUE TITLE
Practical use

### ISSUE THREAD

**Issue by DrPaprikaa** [Marigold/universal-portfolios#42]
Hi,
I just discovered your very cool repo. I was able to play with the parameters on my own historical data using :

    algo = algos.OLMAR(window=5, eps=10)
    result = algo.run(self.df)

The Jupiter Notebook has a "_How to write your own algorithm_" section but it is not, in my sense, very comprehensive.

How can I translate this algo into something that works realtime ? How do I feed the data in ? How do I extract the best model parameters at time t and translate this into actual buy & sell signals ?

I willing to help writting a comprehensive guide on how to do this and make a PR, can you point me in the right direction ?
Thanks,
DrPaprikaa

**Comment by Marigold** [comment]
Hey, this is solely a research project, it's not meant to run in "production". For that, you'll need to connect to a broker (like IB or something, there are tons of packages that can help you with that). OLMAR is such a simple algorithm that once you understand it, you can integrate it into your production code in like ~50 lines.

**Comment by DrPaprikaa** [comment]
Thanks for the quick reply. I already have a production algo and I have been researching strategies for a while now.
I recently came across online portfolio selection algorithms and your repo specifically. I would like to understand how your code works and how I can input it in my personnal backtester, and ultimatly run it live.

**Comment by Marigold** [comment]
Understanding it is pretty easy, for instance [OLMAR](https://github.com/Marigold/universal-portfolios/blob/master/universal/algos/olmar.py) has just 70 lines. The `step` method returns portfolio weights for every time step from available inputs (last portfolio weights and historical prices). That's pretty easy to copy into any backtester.

**Comment by DrPaprikaa** [comment]
Thank you for your answer. I managed to get my head around OLMAR and how it works. Do you have any resources on how to translate the portfolio weights at each time step into the balances of each asset ? I mean, is there a mathematical relation between the weights at t, the balance in quote asset at t and the balances in base assets at t ?
Thanks !
