### ISSUE TITLE
Initial weights in OLMAR

### ISSUE THREAD

**Issue by DrPaprikaa** [Marigold/universal-portfolios#43]
Hi,

I played with [olmar.py](https://github.com/Marigold/universal-portfolios/blob/master/universal/algos/olmar.py) with various `window` and `eps` parameters.

It appears that when setting all of the initial weights to zero (we haven't invested anything yet), the weights `last_b` at the first time step are always set to 1/N, with N the number of stocks in the portfolio. Then, at the next step, all the weights are set to 0 except one which is set to 1. From there, things look normal and realistic weights are assigned to particular stocks.

So it appears that the first two steps are unnecessary and result in unwanted trades and fees at the very beginning of the trading period. 

I also noticed that when setting them already to 1/N, the first step is skipped (logically). One could say that this assumption is valid (we already own said stocks before the start), but the 2nd step remains anyway where everything is sold except one. Is there a way to change this behavior ?

Thanks,
DrPaprikaa

**Comment by Marigold** [comment]
> It appears that when setting all of the initial weights to zero (we haven't invested anything yet), the weights last_b at the first time step are always set to 1/N, with N the number of stocks in the portfolio. Then, at the next step, all the weights are set to 0 except one which is set to 1. From there, things look normal and realistic weights are assigned to particular stocks.

Good catch, that's most likely a bug. I haven't used olmar for quite some time. In case you have a fix, could you create a PR?

> I also noticed that when setting them already to 1/N, the first step is skipped (logically). One could say that this assumption is valid (we already own said stocks before the start), but the 2nd step remains anyway where everything is sold except one. Is there a way to change this behavior?

Sure, you can subclass method `OLMAR.init_weights` and set all weights to zero. You might also have to subclass `update` to avoid weight change penalization when starting with zero weights.

**Comment by DrPaprikaa** [comment]
I checked but couldn't find the issue : maybe some transformation due to the simplex projection ? I don't know.
Closing this issue for now, feel free to re-open it if you have an idea :)
