### ISSUE TITLE
Optimization in CORN algo

### ISSUE THREAD

**Issue by sym44** [Marigold/universal-portfolios#5]
Hi,

While I am reading thru the codes, I found the optimization method in CORN algo a bit confusing:

`   
    def optimal_weights(self, X):
        X = np.mat(X)

        n,m = X.shape
        P = 2 * matrix(X.T * X)
        q = -3 * matrix(np.ones((1,n)) * X).T

        G = matrix(-np.eye(m))
        h = matrix(np.zeros(m))
        A = matrix(np.ones(m)).T
        b = matrix(1.)

        sol = solvers.qp(P, q, G, h, A, b)
        return np.squeeze(sol['x'])
`

In the original paper by Bin L and Stephen Hoi, this should be something like a Prod(B*X) or Sum(log(B*X)). Are these two versions equivalent?

Thanks in advance!

**Comment by Marigold** [comment]
Hm, you're right. What confuses me the most is the term `q = -3 * matrix(np.ones((1,n)) * X).T`, especially the 3 in here... The whole thing looks like markowitz optimization with `q = 3`.

Back to your question - no, they're not equivalent and I'll try to fix it asap.

**Comment by Marigold** [comment]
Fixed it in master & pypi.
