### ISSUE TITLE
Issue on CORRN (slow version)

### ISSUE THREAD

**Issue by Yop127** [Marigold/universal-portfolios#59]
Hello, 
Tried on Binder the slow version of the CORRN algo, there is an error (dimension mismatch on arrays).
![image](https://user-images.githubusercontent.com/63490871/131222753-35a5f35f-e109-44ba-a62d-1a33407c0168.png)

Error should come from here: 
`            X_t = history.iloc[-window:].values.flatten()
            for i in range(window, len(history)):
                X_i = history.iloc[i - window : i - 1].values.flatten()`

In the paper, indexing is different: 
![image](https://user-images.githubusercontent.com/63490871/131222902-ae1b20cf-8790-4b35-9902-3db71b92e129.png)

I guess, we should have ` X_i = history.iloc[i - window : i ].values.flatten()` instead. Will Xcheck with the fast version to see if results match.

**Comment by Marigold** [comment]
Thanks for reporting this, your fix looks correct. I've fixed it and compared to the fast version.
