### ISSUE TITLE
Issue with Mac M1

### ISSUE THREAD

**Issue by rickypp** [Marigold/universal-portfolios#67]
Dear all,
It is impossible to install with Mac M1.
A lot of issue with the version of Scikit-learn, statmodels,cvxopt.
Could you help me?

Thanks

Riccardo

**Comment by Marigold** [comment]
Hi @rickypp, unfortunately I don't have M1 chip so can't test it myself, but it seems to be a known problem and you can try out e.g. https://stackoverflow.com/questions/68620927/installing-scipy-and-scikit-learn-on-apple-m1.

If you find that you need newer versions of some libraries to run it, please let me know and I can try updating them.

**Comment by Marigold** [comment]
Installed latest scikit-learn version, so this might be fixed.
