### ISSUE TITLE
What is difference between `weight` and `step`?

### ISSUE THREAD

**Issue by DexHunter** [Marigold/universal-portfolios#7]
I see the comment for `step` is
> Calculate new portfolio weights.

and `weight` is
> Return weights. Call step method to update portfolio sequentially. Subclass this method only at your own risk.

So if I want to calculate portfolio weight vector, I only need to call `step`?  But I see in `bah.py`, there is no `step` method. So I got really confused by these two functions, Can you explain a bit? Thanks in advance!

**Comment by Marigold** [comment]
Sure. The `Algo` object can run in two modes - sequential or batch. If you use the sequential approach, the `step(self, x, last_b, history)` method will be called for each trading period (week / day / hour) and will return vector of weights for the next period. Most algos implement this method.

However, if your algorithm is simple enough, you can calculate weights for all periods in advance. This is solely for performance reasons. For example in case of CRP (constant rebalanced portfolio) the weight vector is constant. For `BAH` (buy and hold) it's also easy to compute the weight vector in advance.

**Comment by DexHunter** [comment]
@Marigold Thank you very much!
