### ISSUE TITLE
Data information

### ISSUE THREAD

**Issue by r-zip** [Marigold/universal-portfolios#73]
Hi, I'm interested in using the following data files for academic research:
* [djia.csv](https://github.com/Marigold/universal-portfolios/blob/master/universal/data/djia.csv)
* [msci.csv](https://github.com/Marigold/universal-portfolios/blob/master/universal/data/msci.csv)
* [nyse_n.csv](https://github.com/Marigold/universal-portfolios/blob/master/universal/data/nyse_n.csv)
* [nyse_o.csv](https://github.com/Marigold/universal-portfolios/blob/master/universal/data/nyse_o.csv)
* [sp500.csv](https://github.com/Marigold/universal-portfolios/blob/master/universal/data/sp500.csv)
* [tse.csv](https://github.com/Marigold/universal-portfolios/blob/master/universal/data/tse.csv)

Do you have any information on the sources of this data, the time period between prices, etc?

**Comment by Marigold** [comment]
Hey Ryan, my bad for not citing sources. I'll try to dig them up and let you know soon.

**Comment by Marigold** [comment]
It's a standard benchmark dataset that is used for on-line portfolio selection (not saying it's a good one). Here's a description from [this paper](https://deanstreetlab.github.io/papers/papers/Statistical%20Trading/Empirical%20Investigation%20of%20State-Of-The-Art%20Mean%20Reversion%20Strategies%20for%20Equity%20Markets.pdf)
<img width="404" alt="image" src="https://user-images.githubusercontent.com/1550888/159797520-388f0a55-1ca6-49dc-bb13-c2e7424d48c0.png">

Unfortunately, I don't remember when I got that data from. You can try to find the source from one of those papers.

**Comment by r-zip** [comment]
Thank you so much for your quick reply! This is very helpful.
