### ISSUE TITLE
specifying the args of CORN class 

### ISSUE THREAD

**Issue by shayandavoodii** [Marigold/universal-portfolios#83]
Hi, I'm trying to use your code for implementing the CORN strategy, But I'm confused about using it because of poor documentation. So, combining the CORN paper and your codes, I got a light taste, But not adequate.  

So I decided to open an issue to get help from you. [CORN class](https://github.com/Marigold/universal-portfolios/blob/4aece03a141666b7eb9c25f14d1fe9bf333c7320/universal/algos/corn.py#L12) has three optional initial options, namely,  `window`, `rho`, `fast_version` which are explicit. But to get the job done, there are further options in [`init_step`](https://github.com/Marigold/universal-portfolios/blob/4aece03a141666b7eb9c25f14d1fe9bf333c7320/universal/algos/corn.py#L56) module like `X` and [`step_slow`](https://github.com/Marigold/universal-portfolios/blob/4aece03a141666b7eb9c25f14d1fe9bf333c7320/universal/algos/corn.py#L66) module like `x`, `last_b`, `history` which are not explicitly explained about their identity and meaning, But I guess some of them, which I need to know which one is true:  
- `X`: historical relative prices of all stocks in a `pandas.DataFrame` type.
- `x`: maybe a container like a vector that contains the name of equities (stocks)
- `last_b`: latest weights. **(But I don't know what should I pass for the initial round!?)**
- `history`: again, probably historical relative prices of all stocks in a `pandas.DataFrame` type.

Can you please shed light on these variables? Then I can properly give the correct values to these modules.  
Thank you so much.

**Comment by Marigold** [comment]
Hey @shayandavoodii, to run CORN (or any other algorithm) you just call e.g.

```python
S = ... dataframe with RAW prices
algo = CORN(window=10, rho=0.1)
result = algo.run(S)

print(result.summary())
result.plot(weights=False, assets=False, ucrp=True, logy=True);
```

the other methods like `init_step` or `step_slow` are internal (should have been prefixed with underscore) and you don't need even know about them. What is interesting for analysis are methods and attributes of `result` from the code above.

**Comment by Marigold** [comment]
1. Yes, all algorithms have consistent interface and it's enough to call `run()` on them
2. I guess you mean algorithm weights by "optimal weights"? If yes, then it can be accessed as `result.B`. Check out `result.__dict__` for a dictionary of available attributes

**Comment by shayandavoodii** [comment]
> 1. Yes, all algorithms have consistent interface and it's enough to call `run()` on them
> 2. I guess you mean algorithm weights by "optimal weights"? If yes, then it can be accessed as `result.B`. Check out `result.__dict__` for a dictionary of available attributes

But, what are the `result.weights` then?

**Comment by Marigold** [comment]
`result.weights` is a method that is run internally and returns `B`. What you're looking for is `result.B`.

**Comment by shayandavoodii** [comment]
> `result.weights` is a method that is run internally and returns `B`. What you're looking for is `result.B`.

Do you mean, `result.weights` returns the same thing as `result.B`?

**Comment by shayandavoodii** [comment]
> Yes, it's [exactly the same](https://github.com/Marigold/universal-portfolios/blob/master/universal/result.py#L119). Sorry, I thought you were talking about `algo.weights(...)` method. Updated my previous answer.

Thanks a lot!
