### ISSUE TITLE
tools.simplex_project() returns the largest positive vector only? 

### ISSUE THREAD

**Issue by GXY2017** [Marigold/universal-portfolios#91]
For the tools.simplex_proj() function, if my input data is pd.Series([-5,-6, 3, 4]), it returns [0,0,0,1]. I don't think setting the largest to 1 is correct. 

I change to a new func.
````
    def proj(self, s):
        # Replace negative values with 0
        s = s.apply(lambda x: max(x, 0))
        # Calculate the sum of the positive values
        positive_sum = s.sum()
        # If the sum is 0 or 1, return the series as is
        if positive_sum == 0 or positive_sum == 1:
            return s
        # Otherwise, divide each positive value by the sum to make the values sum to 1
        return s.apply(lambda x: x / positive_sum)
````

Correct me if my understanding is wrong. Thank you

**Comment by Marigold** [comment]
Hi @GXY2017, thanks for your interest. By definition simplex projection of A is such a point B on simplex that minimizes distance ||A - B||.

If you check the distances with

```python
A = np.array([-5,-6, 3, 4])
p1 = np.array([0,0,0,1])
p2 = np.maximum(A, 0)
p2 = p2 / p2.sum()

print('Distance to p1: ', np.sqrt(np.sum((A - p1)**2)))
print('Distance to p2: ', np.sqrt(np.sum((A - p2)**2)))
```

You'll see that distance to A from p1 (`tools.simplex_proj()`) is smaller than distance from the point created by your function
```
Distance to p1:  8.888194417315589
Distance to p2:  8.908835330096494
```

That's theory. I don't think it's gonna make any difference in practice.
